---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 15:06
--- 测试入口文件
require("nilDemo1")
require("datatype/booleanDemo")

--- nilTest()
--- booleanPrintTest()