---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 15:06
--- 测试入口文件
require("datatype/nilDemo1")
require("datatype/booleanDemo")
require("datatype/numberDemo")
require("datatype/stringDemo")
require("datatype/tableDemo")
require("datatype/functionDemo")
require("base/variableDemo")
require("base/circulateDemo")
require("base/functionDemo")
require("base/stringDemo")
require("base/arrayDemo")
require("base/metatableDemo")

--- nilTest()
--- booleanPrintTest()
--- numberPrintTest()
--- definedString()
--- stringCalculate()
--- stringAppend()
--- stringLength()
--- TableTest01()
--- TableTest02()
--- functionTest01()
--- functionTest02()


--- variableTest02()
--- variableTest03()

--- whileTest01()
--- forTest01()
--- repeatTest01()
--- ifTest01()

--- funTest06()

--- stringTest01()
--- stringTest02()
--- stringTest05()
--- arrayTest07()

metatableTest03()
