---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 15:06
--- 测试入口文件
require("datatype/nilDemo1")
require("datatype/booleanDemo")
require("datatype/numberDemo")
require("datatype/stringDemo")
require("datatype/tableDemo")

--- nilTest()
--- booleanPrintTest()
--- numberPrintTest()
--- definedString()
--- stringCalculate()
--- stringAppend()
--- stringLength()
