---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 14:59
--- boolean 类型只有两个可选值：true（真） 和 false（假），
--- Lua 把 false 和 nil 看作是 false，其他的都为 true，数字 0 也是 true:

function booleanPrintTest()
    print("******判断true******")
    a = 0==true
    b = nil == true
    print("0是否为true:",a)
    print("nil是否为true:",b)


    print("******判断false******")
    c= nil== false
    d = 0== false
    print("nil是否为false:",c)
    print("0是否为false:",d)
end

