---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 17:54
--- 在 Lua 中，函数是被看作是"第一类值（First-Class Value）"，函数可以存在变量里:


function factorial1(n)
    if n == 0 then
        return 1
    else
        return n * factorial1(n - 1)
    end
end


function testFun(tab,fun)
    for k ,v in pairs(tab) do
        print(fun(k,v));
    end
end


function functionTest01()
    print(factorial1(5))
    factorial2 = factorial1
    print(factorial2(5))
end


function functionTest02()
    tab={key1="val1",key2="val2"};
    testFun(tab,
            function(key,val)--匿名函数
                return key.."="..val;
            end
    );
end
