---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 11:32

function printTest()
    print(type("Hello world"))      --> string
    print(type(10.4*3))             --> number

    print(type(print))              --> function
    print(type(type))               --> function

    print(type(true))               --> boolean


    print(type(nil))                --> nil
    print(type(type(X)))            --> string
end


function nilTest()
    tab1 = { key1 = "val1", key2 = "val2", "val3" }
    for k, v in pairs(tab1) do
        print(k .. " - " .. v)
    end

    print("*******移除部分元素后*******")

    tab1.key1 = nil
    for k, v in pairs(tab1) do
        print(k .. " - " .. v)
    end
end

function nilTest2()
    a = type(x)==nil
    b=type(x)=="nil"
    print("type(x) == nil:",a)
    print("type(x) ==\"nil\":",b)
end


