---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 15:42
--- 字符串

--- 定义字符串
function definedString()
    string1 = "this is string1"
    string2 = 'this is string2'
    print(string1)
    print(string2)
end


--- 字符串运算
function stringCalculate()
    str = "123"
    print("str+123:",str+123)
end

--- 字符串拼接
function stringAppend()
    a = "123"
    b = "error"
    print("a..b = ",a..b)
end

--- 字符串长度
function stringLength()
    a = "123"
    print("a:len = ",#a)
end