---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/5 16:44
--- 数组

function arrayTest01()
    -- 创建一个数组
    local myArray = { 10, 20, 30, 40, 50 }

    -- 访问数组元素
    print(myArray[1])  -- 输出 10
    print(myArray[3])  -- 输出 30
end

function arrayTest02()
    local myArray = { 10, 20, 30, 40, 50 }

    -- 计算数组长度
    local length = #myArray

    print(length) -- 输出 5
end

function arrayTest03()
    local myArray = { 10, 20, 30, 40, 50 }

    -- 遍历数组
    for i = 1, #myArray do
        print(myArray[i])
    end
end

function arrayTest04()
    --- lua 索引默认从 1 开始：
    array = { "Lua", "Tutorial" }
    for i = 0, 2 do
        print(array[i])
    end
end


function arrayTest05()
    array = {}

    for i = -2, 2 do
        array[i] = i * 2
    end

    for i = -2, 2 do
        print(array[i])
    end
end


function arrayTest06()
    -- 创建一个数组
    local myArray = {10, 20, 30, 40, 50}

    -- 添加新元素到数组末尾
    myArray[#myArray + 1] = 60


    -- 循环遍历数组
    for i = 1, #myArray do
        print(myArray[i])
    end
end


function arrayTest07()
    -- 创建一个数组
    local myArray = {10, 20, 30, 40, 50}

    -- 删除第三个元素
    table.remove(myArray, 3)

    -- 循环遍历数组
    for i = 1, #myArray do
        print(myArray[i])
    end
end