---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 18:47
--- 循环

function whileTest01()
    i = 0
    while i < 10
    do
        print(i)
        i = i + 1
    end
end

function f(x)
    print("function")
    return x*2
end

function forTest01()

    --- for var=exp1,exp2,exp3 do
    --     <执行体>
    --  end
    --- var 从 exp1 变化到 exp2，每次变化以 exp3 为步长递增 var，并执行一次 "执行体"。exp3 是可选的，如果不指定，默认为1。
    for i=1,f(10) do
        print(i)
    end
end


function forTest02()
    --- 泛型 for 循环通过一个迭代器函数来遍历所有值，类似 java 中的 foreach 语句。
    a = {"one", "two", "three"}
    for i, v in ipairs(a) do
        print(i, v)
    end
end


function repeatTest01()
    --- 效果与java do while一致
    i = 0
    repeat
        print("i的值",i)
        i = i + 1
    until i > 10
end

function ifTest01()
    if 1 == 1 then
        print("1==1")
    else
        print("1!=1")
    end
end
