---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/4 15:13
--- 函数


local function max(num1, num2)
    if (num1 > num2) then
        result = num1;
    else
        result = num2;
    end
    return result;
end


function funTest01()
    print("两值比较最大值为 ", max(10, 4))
    print("两值比较最大值为 ", max(5, 6))
end

local myprint = function(param)
    print("这是打印函数 -   ##",param,"##")
end

local function add(num1,num2,functionPrint)
    result = num1 + num2
    -- 调用传递的函数参数
    functionPrint(result)
end

function funTest02()
    add(10,20,myprint)
end


local function maximum (a)
    local mi = 1             -- 最大值索引
    local m = a[mi]          -- 最大值
    for i,val in ipairs(a) do
        if val > m then
            mi = i
            m = val
        end
    end
    return m, mi
end

function funTest03()
    a = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
    print("最大值为 ", maximum(a))
end


function add2(...)
    local s = 0
    for i, v in ipairs{...} do   --> {...} 表示一个由所有变长参数构成的数组
        s = s + v
    end
    return s
end


function funTest04()
    print(add2(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
end


function average(...)
    result = 0
    local arg={...}    --> arg 为一个表，局部变量
    for i,v in ipairs(arg) do
        result = result + v
    end
    print("总共传入 " .. #arg .. " 个数")
    return result/#arg
end


function funTest05()
    print("平均值为 ", average(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
end


function average2(...)
    result = 0
    local arg={...}
    for i,v in ipairs(arg) do
        result = result + v
    end
    print("总共传入 " .. select("#",...) .. " 个数")
    return result/select("#",...)
end

function funTest06()
    print("平均值为 ", average2(10,5,3,4,5,6))
end