---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/6 17:41
--- 元表

function metatableTest01()
    ---  table 当成数组
    local arr = {1,2,"abc"}
    table.insert(arr,3,"def")
    table.insert(arr,4,"ghi")
    for k, v in pairs(arr) do
        print(k,v)
    end

    print("----------------------------------------------------------")

    table.remove(arr,1)
    for k, v in pairs(arr) do
        print(k,v)
    end

end


function metatableTest02()
    --- table 当成hashtable
    local dict = {
        k1="v1",
        k2="10086",
        k3="v3"
    }
    table.insert(dict,1,"v4")

    dict["age"] = 18
    dict[10] = "ok"

    for k, v in pairs(dict) do
        print(k,v)
    end

    print("----------------------------------------------------")
    table.remove(dict,2)
    for k, v in pairs(dict) do
        print(k,v)
    end
end


function metatableTest03()
    --- table 关联metatable【本质是一个普通的table,可以包含一些特殊的字段(也称为元方法)】

    local dict = {
        k1="v1",
        k2="10086",
        k3="v3"
    }

    local mt = {
        __index = function(t,k)
            print("__index")
            return "not found"
        end,
        __newindex = function(t,k,v)
            print("__newindex")
            rawset(t,k,v)
        end
    }

    setmetatable(dict,mt)

    print(dict.k6)  -- __index  not found
    print(mt.k6)   -- nil
    -- 只有使用原table才生效

end