---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/4 18:04
--- 字符串

function stringTest01()
    local multilineString = [[
This is a multiline string.
It can contain multiple lines of text.
No need for escape characters.
]]
    print(multilineString)
end


function stringTest02()
    --- 使用 "" 包含上面内容会报错
    local str = "This is a multiline string.It can contain multiple lines of text.No need for escape characters."
    print(str)
end


function stringTest03()
    local str1 = "小青蛙"
    local str2 = "hello"
    print("str1 string.len :", string.len(str1))       ---  9
    print("str1 utf8.len:", utf8.len(str1))            ---  3
    print("str2 string.len :", string.len(str2))       ---  5
    print("str2 utf8.len:", utf8.len(str2))            ---  5
end