---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by anye.
--- DateTime: 2025/3/3 18:32
--- 变量


function variableTest01()
    local site = {}
    site["key"] = "www.runoob.com"
    print(string.format("site[\"key\"]:%s",site["key"]))
    print(string.format("site.key:%s",site.key))
end


function variableTest02()
    a1, a2, a3 = 0, 1
    print(a1,a2,a3)             --> 0   1   nil

    b1,b2 = 1,2,3
    print(b1,b2)                --> 1   2
end


function variableTest03()
    a =1;
    b =2;
    --- 可以实现交换
    a,b = b,a
    print(a,b)
end